### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Masynchin** [trimental/inlyne#1]
How can I install it and what tools do I need for it? OS is macOS.

**Comment by trimental** [comment]
@Masynchin Hi, thanks to your issue I've added a quick installation memo to the README.

`cargo install inlyne` is all you have to do, as even the fonts come pre-bundled. I use macOS as well, however it should work on all operating systems. Please keep in mind its very early days so noticeable bugs or things not working won't be too uncommon.
