### ISSUE TITLE
Scroll wheel too slow

### ISSUE THREAD

**Issue by C0ffeeCode** [trimental/inlyne#13]
Scrolling does not scroll in a direction as much as expected.

Platform: Windows

**Comment by trimental** [comment]
Mm it's a hard one because on macOS it scrolls about what I expect. Are you using a trackpad or a scroll wheel? I might add an option to the config file to allow for changing how many lines it scrolls by.

**Comment by C0ffeeCode** [comment]
I am using a scroll wheel.

**Comment by trimental** [comment]
@C0ffeeCode You can now set how many lines are scrolled using the configuration option introduced in https://github.com/trimental/inlyne/pull/33 so I'll close this as completed :)
