### ISSUE TITLE
Underline alignment regression

### ISSUE THREAD

**Issue by CosmicHorrorDev** [trimental/inlyne#141]
cc @trimental

Just noticed that the PR to add alignment for tables regressed alignment for text vs its underline

**Repro**

```html
<h1 align="center">Some text</p>
```

**Rendered**

![image](https://github.com/trimental/inlyne/assets/30302768/1ce5c3ec-4494-48cf-a51a-529b651a4e62)

You can see that the text is center aligned while the underline is left aligned

This seems to be due to removing the alignment from the `Key` which was used to set the alignment of the `buffer_line`. Admittedly I'm not really familiar enough with the renderer to know how to fix things without likely regressing other parts

**Comment by trimental** [comment]
Yep haha. Currently trying to fix this issue. Getting close to honing in on it but it's a tricky one. Going to need more time to sort it out.
