### ISSUE TITLE
Some missing indentation in codeblocks

### ISSUE THREAD

**Issue by LovecraftianHorror** [trimental/inlyne#16]
Copying & pasting my comment in a new issue instead of replying in a closed one

---

It looks like [this line](https://github.com/trimental/inlyne/commit/fb1f698a24c9905bd951bb3ea33e6136a7b45162#diff-60405aaba3dc351a041fce3e90f17b63dee9a214bc9c35ae6a5126d003100e55R514) (line 514 if the link doesn't focus the right spot) caused a regression on indentation in some codeblocks

![image](https://user-images.githubusercontent.com/30302768/184716721-e6981e36-8599-4d47-8b2e-92ab5faaee1c.png)

Commenting out the conditional _seemed_ to fix the issue, but I don't know if that causes issues elsewhere

**Comment by trimental** [comment]
It causes issues with lists. If you checkout inlyne's README.md with the conditional commented out it causes issues. Basically the space in-between tags needs to be ignored like

```
<ol>
      <li>4 extra spaces before this item</li>
</ol>
```

Ideally html5ever would just ignore them but I think a better way to have handled this would have been to check if the html is preformatted and only push the spaces if they are. Could you try out `else if !str.trim().is_empty() || self.state.text_options.pre_formatted >= 1 ` and see if that fixes issues for you?

**Comment by LovecraftianHorror** [comment]
I'm headed to bed, but I'll give it a try tomorrow 👍

**Comment by LovecraftianHorror** [comment]
That looks like it fixed the issue for me. Thanks!
