### ISSUE TITLE
Support more language types and error display

### ISSUE THREAD

**Issue by Blue-Savage** [trimental/inlyne#21]
https://i.imgur.com/3w5h93E.png

There are two problems with the window in the image.
1, can't display text other than English
2, there is a chance that only part of the content is displayed. Both windows load the same file.

**Comment by trimental** [comment]
With regards to the Chinese characters not being displayed, it's as simple as the bundled San Francisco font not supporting these characters. Bundling fonts definitely makes cross-platform easier but allowing the user to select their own font is something I'd like to support. 

If you could maybe link the file that causes this that would be a great help 😃

**Comment by Blue-Savage** [comment]
You can try it yourselves. The display problem is easily reproducible.
https://github.com/Blue-Savage/temp/raw/main/inlyne.7z

**Comment by trimental** [comment]
Strangely enough everything seems to be rendering for me, perhaps the Chinese is just blinding me to it though. I've included a screenshot of Chinese character rendering using PR https://github.com/trimental/inlyne/pull/22 to select `PingFang SC` as the default font.

<img width="1440" alt="Screenshot 2022-08-17 at 11 58 26 pm" src="https://user-images.githubusercontent.com/40879396/185187385-8de9308d-5d25-4e17-9740-d85e9b5af6b6.png">

**Comment by trimental** [comment]
I'm closing this as resolved since font loading is up to the user and I can't replicate the display issue on the file provided. Please feel free to send any images of the rendering bug to reopen this!
