### ISSUE TITLE
Crashes on scroll wheel

### ISSUE THREAD

**Issue by lnicola** [trimental/inlyne#3]
```
thread 'main' panicked at 'not implemented', src/main.rs:172:30
```

(Linux, Wayland)

**Comment by trimental** [comment]
Thank you for the issue!

macOS doesn't generate anything other than PixelDelta events for mouse scrolls so it slipped through. I've fixed it in commit 65c6244baac5f85fb5209f27e9f24f2533dc38a1 and I'll make a new minor release shortly.

**Comment by lnicola** [comment]
Well, it no longer crashes, but doesn't scroll either (unsurprisingly :smile:).

Zoom would also be nice, since...

![image](https://user-images.githubusercontent.com/308347/184228345-6cfa604d-c138-4218-9973-2a3a1d30bbfc.png)

**Comment by trimental** [comment]
@lnicola Ah sorry for my mistake of course scrolling wouldn't work.. its been a long night of fixing bugs.

Hopefully 9f5b172a1e4a6ab5a329b36858738be8fdf548f4 fixes your issue with scrolling. About the scaling though, it seems that when I tested on sway, wayland would set the window scale to 1, when its about 2 on macOS. I'll investigate this further but for now I've added a command line option to manually set the scale. Ie `inlyne README.md --scale 2.`

**Comment by lnicola** [comment]
> Hopefully https://github.com/trimental/inlyne/commit/9f5b172a1e4a6ab5a329b36858738be8fdf548f4 fixes your issue with scrolling.

I think you've reused the code from the `PixelData` case, so it does scroll, but very slowly. I don't know much about GUI programming, but multiplying with some default line height might help.

`--scale 2` works nicely, thanks.

**Comment by trimental** [comment]
@Inicola Yep this is the problem with scaling, on my Asahi Linux distro it scrolled fast enough by itself.

Tomorrow I'll dive into alacritty's code to check how they're handling Wayland scaling.

**Comment by lnicola** [comment]
Were you testing with a mouse or still a touchpad?

Anyway, don't sweat over this, I love it.
