### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by imranZERO** [trimental/inlyne#35]
When I find a neat tool like this, me and presumably a lot of other people go to the `releases` section to download a binary and try it out. Since this program gains nothing by manually compiling it yourself, it would be nice to see binary builds for the major platforms accompanying every release.

**Comment by trimental** [comment]
Way too many CI minutes later, I got releases to automatically build for linux x64_86, macOS x64_86 + arm, and windows. I've released a [v0.17.1](https://github.com/trimental/inlyne/releases/tag/v0.1.7.1) release to provide these binaries.
