### ISSUE TITLE
Escaped characters eat a single following space

### ISSUE THREAD

**Issue by LovecraftianHorror** [trimental/inlyne#36]
```md
No &space

One & space

Two &  spaces
```

Gets rendered as

![image](https://user-images.githubusercontent.com/30302768/186287271-f2c1e4f9-7e5b-40aa-8ad4-ead7bd78febe.png)

The same thing occurs for other escaped characters like `<` or `>`

**Comment by trimental** [comment]
Whitespaces have really proven to be quite tricky. I think this [commit](144968079ac596971c1a017f22da3c1aca095bd2) should take better care of them and fix this issue.

**Comment by LovecraftianHorror** [comment]
Looks like that fixes. Thanks!
