### ISSUE TITLE
No live code change on Linux

### ISSUE THREAD

**Issue by geri1701** [trimental/inlyne#39]
`.unwrap()` in `src/main.rs:177:18` panics

**Comment by trimental** [comment]
Hello, this seems like it could maybe be an issue with the notify crate. Could you run with the environment variable ’RUST_BACKTRACE=1’ and post the results?

**Comment by geri1701** [comment]
Hello,
RUST_BACKTRACE=full inlyne test.md
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/main.rs:177:18
stack backtrace:
   0:     0x55f2b03c281d - <unknown>
   1:     0x55f2b03e9d2c - <unknown>
   2:     0x55f2b03bb8f1 - <unknown>
   3:     0x55f2b03c3fc5 - <unknown>
   4:     0x55f2b03c3ce6 - <unknown>
   5:     0x55f2b03c4556 - <unknown>
   6:     0x55f2b03c4447 - <unknown>
   7:     0x55f2b03c2cd4 - <unknown>
   8:     0x55f2b03c4179 - <unknown>
   9:     0x55f2af9ebe63 - <unknown>
  10:     0x55f2af9ebf53 - <unknown>
  11:     0x55f2afa920c5 - <unknown>
  12:     0x55f2afb01c7a - <unknown>
  13:     0x55f2b03c9503 - <unknown>
  14:     0x7f3e8a8e878d - <unknown>
  15:     0x7f3e8a9698e4 - clone
  16:                0x0 - <unknown>

**Comment by trimental** [comment]
Mm interesting. This could be because the linux inotify system is only available to root on your system (unlikely) or perhaps if the directory is big enough it maxes out on inotify capacity. I've added this [commit](https://github.com/trimental/inlyne/commit/e6aaa52f7ce3846ca20ede9a51c0759ee2cede3e) to only watch the file path which will help if its the later issue.

Try run it with sudo to see if its the first issue.

**Comment by LovecraftianHorror** [comment]
They probably have a directory without read permissions nested somewhere within the parent

I can reproduce this issue with

```console
$ mkdir some_dir
$ chmod -r some_dir
$ inlyne file.md
```

Changing it to only watching the file should still fix the issue

**Comment by geri1701** [comment]
Yes, the error only occurs when `test.md` is directly in my home directory. If I move `test.md` to a newly created directory, it works fine.

**Comment by geri1701** [comment]
Thank you!
