### ISSUE TITLE
Add support for `<hr/>`

### ISSUE THREAD

**Issue by LovecraftianHorror** [trimental/inlyne#44]
`<hr/>` aka `---` when it comes to markdown draws a horizontal rule that acts as a divider. E.g. vv

---

**Comment by trimental** [comment]
Sorry it's taken me so long to get back to you on these issues, I've been a bit busy this month myself. This should like a very easy to add thing, I'll try to get it working.

**Comment by trimental** [comment]
A couple minutes later commit https://github.com/trimental/inlyne/commit/63849f11b8c4706703a76e74670e669de4867baa is born. A very simple change to just make the spacer element have a boolean `visible` field. Thanks for the suggestion!
