### ISSUE TITLE
Handle streaming decoding of images

### ISSUE THREAD

**Issue by CosmicHorrorDev** [trimental/inlyne#45]
Currently `inlyne` will hold the raw image data in memory. This means that physically large (as in just large width and height) images can take up _a lot_ of memory. Here is the peak memory usage when viewing `bun`'s README for reference

![image](https://user-images.githubusercontent.com/30302768/189545557-87aace25-f57a-4e04-a860-5b8624f99130.png)

As you can see the majority of the memory usage is from holding image data in memory (77 MB when the peak is 110 MB)

I think my current preferred approach for dealing with this would be to save the remote images locally (in the user's cache dir), and perform streaming decoding to read the image on demand when it get's rendered. From my bit of testing it looks like image rendering is handled lazily, so it shouldn't involve reading the image over and over again when rendering

Other approaches could be to hold the remote image in memory and perform streaming decoding when the image gets rendered or to do streaming decoding on the image upfront and store the raw image data in some quick to decompress in-memory blob (like zstd)

The preferred approach would likely depend on how noticeable the delay is when it comes to reading off disk and decoding

---

I'm planning on handling this change (but feel free to work on it if you want)

This is the last memory-hog aspect of `inlyne`. The remaining offenders would appear to be from GPU initialization, glyph crunching, converting non RGBA8 images to RGBA8, and converting the markdown to HTML. At first glance a lot of these look like they would be out of our hands, but I'm still planning on digging in more to check anyways.

**Comment by trimental** [comment]
I think perhaps storing the raw image data in a file and then only loading images that are visible on screen into memory could work. You could then check each time you render for images that are outside of the visible bounds and remove them to save memory. Image drawing should be fairly lazy so this approach might not need too many changes.
