### ISSUE TITLE
A more friendly configuration file

### ISSUE THREAD

**Issue by Frozen1084** [trimental/inlyne#54]
I'm not a programmer and I tried to configure inlyne, but after half an hour I still can't get "inlyne.toml" to work.
dirs seems to be a library? I really don't know how to use it.
Why not read "inlyne.toml" from the same directory as inlyne.exe?
This is portable and very easy to use. Why don't we use it this way?

Or the command line argument, "-conf inlyne.toml"

**Comment by trimental** [comment]
Hello I agree that dirs can be a little confusing, especially for non Linux platforms. Generally though it's not wise to store configuration files next to the executable, except maybe on windows. Maybe I'll add the config directories to the README instead. What platform are you using?

**Comment by Frozen1084** [comment]
Thanks. Yes, I'm using win-10. I really want the exe and toml to be in the same directory.


By the way.
Can you compile a dll version? So that I can call it with a script and use it as a gui control for displaying "markdown".

**Comment by trimental** [comment]
You need to create a folder called inlyne like `C:\Users\Alice\AppData\Roaming\inlyne\inlyne.toml`. You could store the executable in that folder and add it to your system path.

I don't quite understand the DLL request. Do you mean that you'd like to inbed inlyne into another application's gui or do you mean you want to start inlyne from another app?

**Comment by Frozen1084** [comment]
Is it very difficult to read the files in the exe directory? I still want the software to be portable so that the configuration is not lost when reinstalling the system.

----

Yes, just like the script uses mpv.dll to display the video.

**Comment by trimental** [comment]
It wouldn't be hard to implement but storing configuration files next to executables doesn't make a lot of sense to me. Executables breaking when you move them out their folder is a windows problem I don't want to copy. I'd be open to a CLI config argument though.

If you're talking about batch scripts, you can execute inlyne with the start command. Inlyne is a binary rust program not a library, it doesn't have any public function calls to expose through a DLL. I don't personally feel the need to turn inlyne into a library but I'd welcome anyone who wanted to tackle that.

**Comment by Frozen1084** [comment]
Thank you.

The script I'm using is AutoHotkey, which is a scripting software for the Win platform.

 The problem with Inlyne as a standalone md viewer is that its interface is too rudimentary.
It has no means of interaction other than displaying the md file correctly, no menus when selecting text, and more ways to manipulate it.
It is almost indistinguishable from a control dedicated to displaying md files. If it were a control, I could have used AutoHotkey to complete the interaction for it. But unfortunately I can't use it as a control.

**Comment by Frozen1084** [comment]
No, the issue is not that complicated.
I used to use AutoHotkey to call mpv to play videos.

It has two methods.
1, AutoHotkey creates a window, calls mpv.exe with the window ID as the start parameter. mpv.exe creates a video window that will be displayed as a control of the AutoHotkey window.
2, AutoHotkey creates a window, loads dll.dll and calls mpv_set_option(), which will set the window as mpv's parent window. This will also display mpv as a control.

Both methods are not complicated. If we apply it to inlyne, then we only need to add a few startup parameters. For example "-hWndParent 2327 -show_wh 200x200"

As long as the support is inputting the parent window as an argument.


By the way, a question for you.
If I try to compile an inlyne.dll, exposing a load_md() function. It has only four arguments.
1-md_path, 2-parent_hwnd, 3-show_w, 4-show_h
Which function would be the best one for me to start modifying?

**Comment by trimental** [comment]
Okay if you want to set a parent window on windows, you can use [this](https://docs.rs/winit/latest/i686-pc-windows-msvc/winit/platform/windows/trait.WindowBuilderExtWindows.html#tymethod.with_parent_window). Unfortunately this feature you'd have to implement yourself since I don't want to add non cross platform arguments.

As for your question. You need to modify main(). Create your own Args struct using md_path instead of getting it through new(). And pass the window arguments to the inlyne::new() function, then use those arguments to call subfunctions on the window object at https://github.com/trimental/inlyne/blob/0f6c314ba4f1961f980a86a7c1db347a226b46b6/src/main.rs#L202. Like the function I linked above.

**Comment by Frozen1084** [comment]
Thank you very much, this is very helpful.
