### ISSUE TITLE
Consider pushing a tag when doing releases

### ISSUE THREAD

**Issue by LovecraftianHorror** [trimental/inlyne#7]
I put together an [`inlyne` AUR package](https://aur.archlinux.org/packages/inlyne) since a browserless markdown viewer is something I've wanted for quite a while!

It would make the `PKGBUILD` a lot simpler if some `vX.Y.Z` or `X.Y.Z` tag was pushed for each release. At the moment I'm basing releases off the commit hash that bumps the `version`

**Comment by trimental** [comment]
@LovecraftianHorror Amazing thanks for creating an AUR package.

I'll be glad to start doing tag releases. Once I get a few more commits I'll release v0.1.6 with tags :)

**Comment by LovecraftianHorror** [comment]
Sounds great!

I'll go ahead and close this then :)

**Comment by trimental** [comment]
@LovecraftianHorror https://github.com/trimental/inlyne/releases/tag/v0.1.6. Managed to get in quote blocks quickly and fix one or two things before release.

**Comment by LovecraftianHorror** [comment]
Great to see a release! :partying_face: 

I'm on my lunchbreak, so I was looking over things. It looks like [this line](https://github.com/trimental/inlyne/commit/fb1f698a24c9905bd951bb3ea33e6136a7b45162#diff-60405aaba3dc351a041fce3e90f17b63dee9a214bc9c35ae6a5126d003100e55R514) (line 514 if the link doesn't focus the right spot) caused a regression on indentation in some codeblocks

![image](https://user-images.githubusercontent.com/30302768/184716721-e6981e36-8599-4d47-8b2e-92ab5faaee1c.png)

Commenting out the conditional _seemed_ to fix the issue, but I don't know if that causes issues elsewhere

---

On a related note; I'm planning on getting snapshot testing setup for the interpreter, so that hopefully we can notice these issues earlier in the future, but that will have to wait till next weekend :smile:

**Comment by LovecraftianHorror** [comment]
Also thanks for [pushing a tag](https://github.com/LovecraftianHorror/arch-pkgbuilds/commit/1d9c1a47084e4b536b0d5ee201a0d18389639063)!
