### ISSUE TITLE
Add Q and Escape to the default Quit keybindings

### ISSUE THREAD

**Issue by coastalwhite** [trimental/inlyne#81]
Q and Escape should be added to the default keybindings to quit.

**Comment by CosmicHorrorDev** [comment]
@trimental you okay if I just go ahead and add vim-like to the defaults? It's pretty easy for people to override the changes with `[keybindings.extra]`

**Comment by trimental** [comment]
@CosmicHorrorDev yep totally happy with that. Would be a pretty useful binding.

**Comment by CosmicHorrorDev** [comment]
Escape along with a whole slew of vim-like bindings are now included in the default bindings
