### ISSUE TITLE
Allow for flag to overwrite config location

### ISSUE THREAD

**Issue by coastalwhite** [trimental/inlyne#84]
It would be very useful to have a `--config` flag to select a custom configuration file.

**Comment by CosmicHorrorDev** [comment]
I would be okay with this (along with something like `--no-config` to easily skip using a config file)

Just to get perspective for workflows, I'm curious if you have some specific motivating use-case for this

**Comment by coastalwhite** [comment]
This is very useful to alias `inlyne` to `inlyne --config <config.toml>` in case you want to use a separate environment for a while. This would also be useful, for example, if you wanted to embed this program into another program.

**Comment by trimental** [comment]
@CosmicHorrorDev do you mean --no-config to skip using the config from the default location? Otherwise I'm guessing you just wouldn't put a --config flag.

**Comment by CosmicHorrorDev** [comment]
`--no-config` to skip reading config files altogether (e.g. how `ripgrep` uses it). I've seen some other names for it like `--clean` for vim

It's useful for making sure you get a clean environment for things like bug reports

**Comment by trimental** [comment]
Might be useful for testing

**Comment by CosmicHorrorDev** [comment]
@coastalwhite feel free to work on this if you want to btw. I've got other stuff I need to get through today, so I won't be able to start on it till sometime next week
