### ISSUE TITLE
Bug: emojis like 🚀 are not shown

### ISSUE THREAD

**Issue by chaosprint** [trimental/inlyne#86]

**Comment by CosmicHorrorDev** [comment]
We don't have font fallback setup for using multiple fonts to render the same block of text, so that all depends on what the font that gets picked for rendering supports

**Comment by nicoburns** [comment]
I think you could fix this (and generally greatly improve text rendering quality) by using https://github.com/pop-os/cosmic-text for test

**Comment by CosmicHorrorDev** [comment]
I've been following it's development, and it's definitely been on my wishlist to use for this project. Just haven't had the time to try switching over

**Comment by CosmicHorrorDev** [comment]
Just noticed that cosmic-text is getting integrated into `iced`. May be able to pull some inspiration from those changes

https://github.com/iced-rs/iced/pull/1830

**Comment by trimental** [comment]
![image](https://github.com/trimental/inlyne/assets/40879396/1e4bbcd1-ae5e-41cd-8128-1ea50b1e42b0)

Got cosmic text 80% working but with severe performance penalties in it's current state. Hope to fix things up to a PR ready state soon!

**Comment by nicoburns** [comment]
Amazing. Do you have a glyph cache setup yet? It's my understanding that this is key to good performance with cosmic text as glyph rendering is done on the CPU and relatively slow.

**Comment by trimental** [comment]
Not yet. I've only done enough to just get it in a semi working state. Getting everything working smoothly is going to require quite a bit of redesign.
