### ISSUE TITLE
Windows build requires Windows SDK

### ISSUE THREAD

**Issue by jnnnnn** [trimental/inlyne#88]
following https://github.com/iced-rs/iced/issues/78 I found that installing the [Windows SDK](https://developer.microsoft.com/en-US/windows/downloads/windows-sdk/) solved a final link error after running `cargo install inlyne`:

    LINK : fatal error LNK1181: cannot open input file 'd3d12.lib'

**Comment by CosmicHorrorDev** [comment]
This is certainly good to have in the issue history for anyone else who runs into this problem :+1:
