### ISSUE TITLE
Extended Syntax - Footnotes would be very nice.

### ISSUE THREAD

**Issue by theherk** [trimental/inlyne#90]
Would be excellent to support Extended Syntax, expecially [Footnotes](https://www.markdownguide.org/extended-syntax/#footnotes).

Like this[^1].

```markdown
Like this[^1].

[^1]: A [footnote](https://www.markdownguide.org/extended-syntax/#footnotes)
```

[^1]: A [footnote](https://www.markdownguide.org/extended-syntax/#footnotes)

**Comment by trimental** [comment]
This is something I'll look into, seems like it would be a nice addition. Thanks.

**Comment by CosmicHorrorDev** [comment]
`comrak` has [support for defining plugins](https://docs.rs/comrak/latest/comrak/fn.format_commonmark_with_plugins.html), but I haven't looked to see how implementing a plugin would go. Reasonably common extensions like this would be general enough that they should live in a standalone crate that we develop / may already have an existing crate
